### ISSUE TITLE
download/installation info on the website?

### ISSUE THREAD

**Issue by pnwamk** [ponylang/ponylang.github.io#118]
I couldn't easily find any info regarding _recommended_ way(s) to download and/or install Pony on the website (i.e. are there nightly/release builds? do most people build from source? should I grab it from a package manager? etc). Maybe I didn't look hard enough... but a link to something like that should jump off the landing page for Pony, IMHO. It would make it a lot easier for newcomers to quickly saddle up =)

Here are a few examples of programming languages whose sites have a download link fairly visible on the main page:

+ https://www.haskell.org
+ https://ocaml.org
+ https://www.rust-lang.org/
+ https://racket-lang.org

**Comment by SeanTAllen** [comment]
Thanks for the suggestion. We aren't going to go in that direction but I am leaving this open as a reminder that the first page needs more, go here for X type info as its still the placeholders I put in a while ago.

**Comment by SeanTAllen** [comment]
I'm going to work on this this weekend. Thanks for the inspiration @pnwamk.

**Comment by ruuda** [comment]
I just had the same experience. I heard about Pony via various channels, and Pony sounded interesting to me so I wanted to try it. To me, the natural thing to do was to go to the website.

I have two suggestions:

 * Name pages and links after their content, rather than their target audience.
 * Link the tutorial from the frontpage. “New to Pony? Start here” should really link to the tutorial. Getting help and opening issues are not things to start with, they are for when you get stuck *after* you’ve started.

 I’ll write down my thought process below, in the hope that it will be useful for improving the user experience of the website.

 * * *

> We’ve set up the website to be based on who you are.

Okay, that is a bit weird ... who I am will probably not change a lot over time, but I imagine I might be looking for different things (a download link now, likely API documentation later).

> * New to Pony?
> * Learning Pony?
> * Existing Pony User looking for stuff?

I am new to Pony. Hopefully that page will contain a download link.

*\*clicks New to Pony\**

> **What is Pony?**
> Pony is an open-source, object-oriented, actor-model, capabilities-secure, high-performance programming language.

Hmm, no, this page tells me what Pony is, but I already knew that.

*\*hits the back button\**

> * New to Pony?
> * Learning Pony?
> * Existing Pony User looking for stuff?

Well, I do want to learn Pony. Probably that page will link to a tutorial or some introductory documentation, and the first thing it is going to do is explain how to obtain Pony.

*\*clicks Learning Pony\**

> **Getting help**
> ...
> Mailing list, IRC
> ...
> Open an issue
> ...
> **Reference capabilities**
> ...
> **A note about code samples**
> ...

Ok, so there is a mailing list and an IRC channel, but hopefully I don’t have to go there to ask for a download link. There is some stuff about reference capabilities, that is probably the thing that I am going to struggle with. And there is a warning of some kind.

To be fair, I should have noticed the “Tutorial” link here, which does indeed point to the installation instructions early on. Unfortunately I missed it.

Maybe I am an existing user then? Existing users occasionally need to download the toolchain, don’t they?

*\*clicks Existing User in the menu on the left\**

> Pony LLDB Cheatsheet
> Pony Performance Cheatsheet

Nope, that’s not it either. Let’s check the homepage one more time.

*\*clicks the logo in the top left corner\**

And that is how I accidentally ended up on the GitHub page, which does contain installation instructions pretty early on in the readme.

**Comment by SeanTAllen** [comment]
Pushing a change to make this more obvious this afternoon.
